/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Mohamed Faryed
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of Port_PBcfg.c does not match the expected version"
#endif

Port_ConfigType PinConfig_array[] =
{                       /*PORT A */
  {PORT_A, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN5, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN6, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_A, PIN7, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
                        /*PORT B */
  {PORT_B, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN5, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN6, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_B, PIN7, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
                        /*PORT C */
  {PORT_C, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, UN_CHANGE},
  {PORT_C, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, UN_CHANGE},
  {PORT_C, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, UN_CHANGE},
  {PORT_C, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, UN_CHANGE},
  {PORT_C, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_C, PIN5, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_C, PIN6, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_C, PIN7, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
                        /*PORT D */
  {PORT_D, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN5, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN6, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_D, PIN7, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
                        /*PORT E */
  {PORT_E, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN5, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN6, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_E, PIN7, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
                        /*PORT F */
  {PORT_F, PIN0, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_F, PIN1, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_F, PIN2, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_F, PIN3, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE},
  {PORT_F, PIN4, PORT_PIN_IN, UN_ALT, GPIO_MODE, OFF, PIN_LOW, CHANGE}
};

